// @ts-check
import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'
import tseslint from 'typescript-eslint'

export default defineConfig(
  globalIgnores(['**/dist', 'apps/web/src/client']),
  {
    name: 'api',
    files: ['apps/api/**/*.ts'],
    languageOptions: { globals: globals.node },
    extends: [js.configs.recommended, tseslint.configs.recommended],
  },
  {
    name: 'web',
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    languageOptions: { globals: globals.browser },
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      // react-hooks v7 ships its preset in eslintrc flavor (string plugins),
      // so pull the rules in instead of extending the preset object.
      { rules: reactHooks.configs.recommended.rules },
      reactRefresh.configs.vite,
      // shadcn/ui components export variants (cva) next to the component.
      { rules: { 'react-refresh/only-export-components': ['warn', { allowConstantExport: true }] } },
    ],
  },
  {
    // Vendored shadcn/ui code: components export cva variants alongside the
    // component, which fast refresh cannot optimize. Regenerated by the
    // shadcn CLI, so suppress in config rather than annotating the file.
    name: 'web-vendor-shadcn',
    files: ['apps/web/src/components/ui/**'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  {
    name: 'e2e',
    files: ['apps/e2e/**/*.ts'],
    languageOptions: { globals: globals.node },
    extends: [js.configs.recommended, tseslint.configs.recommended],
  },
  {
    name: 'web-node-context',
    files: ['apps/web/vite.config.ts'],
    languageOptions: { globals: globals.node },
  },
)
