// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AvailabilityListData, AvailabilityListErrors, AvailabilityListResponses, BookingsCreateData, BookingsCreateErrors, BookingsCreateResponses, BookingsListData, BookingsListResponses, EventTypesCreateData, EventTypesCreateErrors, EventTypesCreateResponses, EventTypesListData, EventTypesListResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const availabilityList = <ThrowOnError extends boolean = false>(options: Options<AvailabilityListData, ThrowOnError>): RequestResult<AvailabilityListResponses, AvailabilityListErrors, ThrowOnError> => (options.client ?? client).get<AvailabilityListResponses, AvailabilityListErrors, ThrowOnError>({ url: '/availability', ...options });

export const bookingsList = <ThrowOnError extends boolean = false>(options?: Options<BookingsListData, ThrowOnError>): RequestResult<BookingsListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<BookingsListResponses, unknown, ThrowOnError>({ url: '/bookings', ...options });

export const bookingsCreate = <ThrowOnError extends boolean = false>(options: Options<BookingsCreateData, ThrowOnError>): RequestResult<BookingsCreateResponses, BookingsCreateErrors, ThrowOnError> => (options.client ?? client).post<BookingsCreateResponses, BookingsCreateErrors, ThrowOnError>({
    url: '/bookings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const eventTypesList = <ThrowOnError extends boolean = false>(options?: Options<EventTypesListData, ThrowOnError>): RequestResult<EventTypesListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<EventTypesListResponses, unknown, ThrowOnError>({ url: '/event-types', ...options });

export const eventTypesCreate = <ThrowOnError extends boolean = false>(options: Options<EventTypesCreateData, ThrowOnError>): RequestResult<EventTypesCreateResponses, EventTypesCreateErrors, ThrowOnError> => (options.client ?? client).post<EventTypesCreateResponses, EventTypesCreateErrors, ThrowOnError>({
    url: '/event-types',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
