// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiError = {
    code: string;
    message: string;
};

export type Booking = {
    id: string;
    eventTypeId: string;
    guestName: string;
    guestEmail: string;
    start: string;
    createdAt: string;
};

export type CreateBooking = {
    eventTypeId: string;
    start: string;
    guestName: string;
    guestEmail: string;
};

export type DayAvailability = {
    date: string;
    startTimes: Array<string>;
};

export type ErrorBody = {
    error: ApiError;
};

export type EventType = {
    id: string;
    title: string;
    description?: string;
    durationMinutes: number;
};

export type OwnerBooking = Booking & {
    eventTypeTitle: string;
    durationMinutes: number;
};

export type AvailabilityListData = {
    body?: never;
    path?: never;
    query: {
        eventTypeId: string;
        from: string;
        to: string;
    };
    url: '/availability';
};

export type AvailabilityListErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorBody;
    /**
     * The server cannot find the requested resource.
     */
    404: ErrorBody;
    /**
     * Client error
     */
    422: ErrorBody;
};

export type AvailabilityListError = AvailabilityListErrors[keyof AvailabilityListErrors];

export type AvailabilityListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<DayAvailability>;
};

export type AvailabilityListResponse = AvailabilityListResponses[keyof AvailabilityListResponses];

export type BookingsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bookings';
};

export type BookingsListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<OwnerBooking>;
};

export type BookingsListResponse = BookingsListResponses[keyof BookingsListResponses];

export type BookingsCreateData = {
    body: CreateBooking;
    path?: never;
    query?: never;
    url: '/bookings';
};

export type BookingsCreateErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorBody;
    /**
     * The server cannot find the requested resource.
     */
    404: ErrorBody;
    /**
     * The request conflicts with the current state of the server.
     */
    409: ErrorBody;
    /**
     * Client error
     */
    422: ErrorBody;
};

export type BookingsCreateError = BookingsCreateErrors[keyof BookingsCreateErrors];

export type BookingsCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: Booking;
};

export type BookingsCreateResponse = BookingsCreateResponses[keyof BookingsCreateResponses];

export type EventTypesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/event-types';
};

export type EventTypesListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<EventType>;
};

export type EventTypesListResponse = EventTypesListResponses[keyof EventTypesListResponses];

export type EventTypesCreateData = {
    body: EventType;
    path?: never;
    query?: never;
    url: '/event-types';
};

export type EventTypesCreateErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ErrorBody;
    /**
     * Client error
     */
    422: ErrorBody;
};

export type EventTypesCreateError = EventTypesCreateErrors[keyof EventTypesCreateErrors];

export type EventTypesCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: EventType;
};

export type EventTypesCreateResponse = EventTypesCreateResponses[keyof EventTypesCreateResponses];
